services:
  db:
    build: ./database
    restart: always
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
  
  backend:
    build: ./backend/
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_vol:
    driver: local