services:
  db:
    build: ./database
    restart: always
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      # Set to a larger number if datasets are large or
      # if your machine cant import them fast enough.
      # Consider starting the database service separately
      # before the backend if its startup takes too much time.
      interval: 30s
      timeout: 20s
      retries: 5
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: app-build
    command: ["node", "dist/index.js"]
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  
  backend-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: app-test
    command: ["npm", "run", "test"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_vol:
    driver: local