services:
  db:
    build: ./database
    restart: always
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  
  # frontend:
  #   build: ./frontend/
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  db_vol:
    driver: local