name: Application Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_NAME: testdb
      CORS_ORIGIN: http://localhost:3000
    name: Test building the app and testing the backend
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build and run backend-tests image
      run: docker-compose --file docker-compose.yml up --build backend-tests
